spring:
  datasource:
    username: pavan
    password: secpass
    url: jdbc:postgresql://localhost:5432/expenses
    driver-class-name: org.postgresql.Driver
  boot:
    admin:
      client:
        url: http://localhost:9999
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka